version: "3.1"
services:
  client-prod:
    container_name: client-prod
    build:
      context: ./
      args:
        ports_expose: 80
        supervisor: supervisor-prod.conf
        nginx: nginx-prod.conf
    volumes:
      - ./:/home/client
      - /mnt/logs/client:/logs
    environment:
      NODE_ENV: production
    ports:
      - "80:80"